mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('spark.urls', namespace="roots")),
    url(r'^spark/', include('spark.urls', namespace="spark")),
    url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^opt/$', views.opt, name='opt'),
)

spark/urls.py
from django.conf.urls import patterns, url

from spark import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^opt/$', views.opt, name='opt'),
)

spark/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):              # __unicode__ on Python 2
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

# import pyRserve
import json

from polls.models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


def opt(request):
    # conn = pyRserve.connect()
    # conn.eval('rm(list=ls())')
    # conn.r.input_total_amt = int(request.GET['budget'])
    # res2 = conn.eval("source('C:/Users/yixiang/Desktop/opt_total.R')")
    # result = json.loads(res2['value'])
    # conn.close()
    # return HttpResponse(json.dumps(result), content_type='application/json')
    return HttpResponse(json.dumps('sample data'), content_type='application/json')

spark/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

# import pyRserve
import json

from spark.models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'common/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'common/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'common/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'common/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('spark:results', args=(p.id,)))


def opt(request):
    # conn = pyRserve.connect()
    # conn.eval('rm(list=ls())')
    # conn.r.input_total_amt = int(request.GET['budget'])
    # res2 = conn.eval("source('C:/Users/yixiang/Desktop/opt_total.R')")
    # result = json.loads(res2['value'])
    # conn.close()
    # return HttpResponse(json.dumps(result), content_type='application/json')
    return HttpResponse(json.dumps('sample data'), content_type='application/json')

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sparkzones - Data enlighten the world</title>

    {% load staticfiles %}

    <link rel="icon" href="{% static 'polls/favicon.ico' %}">
      <!-- Bootstrap core CSS -->
    <link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <!-- Bootstrap theme -->
    <link href="{% static 'polls/css/bootstrap-theme.min.css' %}" rel="stylesheet"/>
    <!-- Bootstrap slider -->
    <link href="{% static 'polls/css/bootstrap-slider.css' %}" rel="stylesheet"/>
    <!-- nvd3 theme -->
    <link href="{% static 'polls/css/nv.d3.min.css' %}" rel="stylesheet"/>

    <!-- Custom styles for this project -->
    <link href="{% static 'polls/theme.css' %}" rel="stylesheet"/>

    <!-- jquery and bootstrap -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'polls/scripts/bootstrap.min.js' %}"></script>
    <script src="{% static 'polls/scripts/bootstrap-slider.js' %}"></script>

    <!-- nvd3 -->
    <script src="{% static 'polls/scripts/nvd3/d3.v3.min.js' %}"></script>
    <script src="{% static 'polls/scripts/nvd3/nv.d3.min.js' %}"></script>
    <!-- including all the components so I don't have to minify every time I test in development -->
    <script src="{% static 'polls/scripts/nvd3/tooltip.js' %}"></script>
    <script src="{% static 'polls/scripts/nvd3/utils.js' %}"></script>
    <script src="{% static 'polls/scripts/nvd3/axis.js' %}"></script>
    <script src="{% static 'polls/scripts/nvd3/legend.js' %}"></script>
    <!-- nvd3 discreteBar-->
{#    <script src="{% static 'polls/scripts/nvd3/discreteBar.js' %}"></script>#}
{#    <script src="{% static 'polls/scripts/nvd3/discreteBarChart.js' %}"></script>#}
    <!-- nvd3 multiBar vertical -->
    <script src="{% static 'polls/scripts/nvd3/multiBar.js' %}"></script>
    <script src="{% static 'polls/scripts/nvd3/multiBarChart.js' %}"></script>
    <!-- nvd3 multiBar horizontal-->
    <script src="{% static 'polls/scripts/nvd3/multiBarHorizontal.js' %}"></script>
    <script src="{% static 'polls/scripts/nvd3/multiBarHorizontalChart.js' %}"></script>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'polls/scripts/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body role="document">

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Sparkzones</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% comment %}<li class="active"><a href="#">Home</a></li>{% endcomment %}
            <li><a href="#content-service">Services</a></li>
            <li><a href="#content-solution">Solutions</a></li>
            <li><a href="#content-case">Case Study</a></li>
            <li><a href="#sign-up">Sign Up</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">More<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#content-about">About</a></li>
                <li><a href="#content-contact">Contact</a></li>
                <li class="divider"></li>
                {% comment %}<li class="dropdown-header">Nav header</li>{% endcomment %}
                <li><a href="#">Client Login</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!--<div class="container theme-showcase" role="main">

    </div>  /container -->
    {% block content %}
    {% endblock %}
    <footer>
        <div class="text-center">
            Copyright @2014, All Rights Reserved. Sparkzones Inc.
        </div>
    </footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'polls/scripts/docs.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'polls/scripts/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

spark/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sparkzones - Data enlighten the world</title>

    {% load staticfiles %}

    <link rel="icon" href="{% static 'spark/favicon.ico' %}">
      <!-- Bootstrap core CSS -->
    <link href="{% static 'spark/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <!-- Bootstrap theme -->
    <link href="{% static 'spark/css/bootstrap-theme.min.css' %}" rel="stylesheet"/>
    <!-- Bootstrap slider -->
    <link href="{% static 'spark/css/bootstrap-slider.css' %}" rel="stylesheet"/>
    <!-- nvd3 theme -->
    <link href="{% static 'spark/css/nv.d3.min.css' %}" rel="stylesheet"/>

    <!-- Custom styles for this project -->
    <link href="{% static 'spark/theme.css' %}" rel="stylesheet"/>

    <!-- jquery and bootstrap -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'spark/scripts/bootstrap.min.js' %}"></script>
    <script src="{% static 'spark/scripts/bootstrap-slider.js' %}"></script>

    <!-- nvd3 -->
    <script src="{% static 'spark/scripts/nvd3/d3.v3.min.js' %}"></script>
    <script src="{% static 'spark/scripts/nvd3/nv.d3.min.js' %}"></script>
    <!-- including all the components so I don't have to minify every time I test in development -->
    <script src="{% static 'spark/scripts/nvd3/tooltip.js' %}"></script>
    <script src="{% static 'spark/scripts/nvd3/utils.js' %}"></script>
    <script src="{% static 'spark/scripts/nvd3/axis.js' %}"></script>
    <script src="{% static 'spark/scripts/nvd3/legend.js' %}"></script>
    <!-- nvd3 discreteBar-->
{#    <script src="{% static 'common/scripts/nvd3/discreteBar.js' %}"></script>#}
{#    <script src="{% static 'common/scripts/nvd3/discreteBarChart.js' %}"></script>#}
    <!-- nvd3 multiBar vertical -->
    <script src="{% static 'spark/scripts/nvd3/multiBar.js' %}"></script>
    <script src="{% static 'spark/scripts/nvd3/multiBarChart.js' %}"></script>
    <!-- nvd3 multiBar horizontal-->
    <script src="{% static 'spark/scripts/nvd3/multiBarHorizontal.js' %}"></script>
    <script src="{% static 'spark/scripts/nvd3/multiBarHorizontalChart.js' %}"></script>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'spark/scripts/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body role="document">

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Sparkzones</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% comment %}<li class="active"><a href="#">Home</a></li>{% endcomment %}
            <li><a href="#content-service">Services</a></li>
            <li><a href="#content-solution">Solutions</a></li>
            <li><a href="#content-case">Case Study</a></li>
            <li><a href="#sign-up">Sign Up</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">More<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#content-about">About</a></li>
                <li><a href="#content-contact">Contact</a></li>
                <li class="divider"></li>
                {% comment %}<li class="dropdown-header">Nav header</li>{% endcomment %}
                <li><a href="#">Client Login</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!--<div class="container theme-showcase" role="main">

    </div>  /container -->
    {% block content %}
    {% endblock %}
    <footer>
        <div class="text-center">
            Copyright @2014, All Rights Reserved. Sparkzones Inc.
        </div>
    </footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'spark/scripts/docs.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'spark/scripts/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

spark/templates/common/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'spark:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

spark/templates/common/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'spark:detail' question.id %}">Vote again?</a>